<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>feature</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~C</string>
	<key>name</key>
	<string>Cucumber Plain Text Feature</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#scenario_keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#description</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#feature_keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line_keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pending_keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*(#.*)</string>
		</dict>
		<key>description</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.language.cucumber.feature.description</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.language.cucumber.feature.description</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(As an|As a|I want|So that|In order)(.*)</string>
		</dict>
		<key>feature_keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.language.cucumber.feature</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.language.cucumber.feature.title</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(Funzionalità|Arwedd|フィーチャ|Egenskap|Fonction|Feature|Funktionalität|Функционал|Característica|Omadus|Fitur|Właściwość|خاصية|Egenskab|Functionaliteit|功能:)(.*)\b</string>
		</dict>
		<key>line_keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.language.cucumber.feature.scenario.line</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(Dato|DatoLoScenario|Ma|E|Allora|Quando|Più esempi|anrhegedig a|Anrhegedig scenario|Ond|A|Yna|Pryd|Hychwaneg enghreifftiau|前提|前提シナリオ|しかし|かつ|ならば|もし|他のサンプル|Gitt|GittScenario|Men|Og|Så|Når|Flere eksempler|Soit|SoitScenario|Mais|Et|Alors|Lorsque|Plus d'exemples|Given y'all|GivenScenario|But y'all|And y'all|Then y'all|When y'all|More Examples|Gegeben sei|GegebenesSzenario|Aber|Und|Dann|Wenn|Сначала|ДанныйСценарий|Но|И|То|Если|Dado|DadoElEscenario|Pero|Y|Entonces|Cuando|Más ejemplos|Eeldades|EeldadesStsenaariumit|Kuid|Ja|Siis|Kui|DadoOCenário|Mas|Então|Dengan|DenganSkenario|Tapi|Dan|Maka|Ketika|Contoh Tambahan|Dane|DanyScenariusz|Ale|Oraz|Wtedy|Jeżeli|WięcejPrzykładów|بفرض|بفرض سيناريو معين|لكن|و|اذاً|متى|امثلة اكثر|Givet|GivetScenario|Och|När|GivetScenarie|Gegeven|GegevenScenario|Maar|En|Als|Meer voorbeelden|Given|But|And|Then|When|假如|引用场景|但是|而且|那么|当)\b</string>
		</dict>
		<key>pending_keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.language.cucumber.feature.scenario.pending.line</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.language.cucumber.feature.scenario.pending.line</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(Pending)(.*)\b</string>
		</dict>
		<key>scenario_keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.language.cucumber.feature.scenario</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.language.cucumber.feature.scenario.title</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(Scenario|シナリオ|Szenario|Сценарий|Escenario|Stsenaarium|Cenário|Skenario|Scenariusz|سيناريو|Scenarie|场景:)(.*)\b</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s+'([^']+)'[\b\s]+</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.cucumber.feature</string>
	<key>uuid</key>
	<string>85E2C52C-9B16-4A54-81E7-6D8D3ADAEFA8</string>
	<key>ﬁrstLineMatch</key>
	<string>Funzionalità|Arwedd|フィーチャ|Egenskap|Fonction|Feature|Funktionalität|Функционал|Característica|Omadus|Fitur|Właściwość|خاصية|Egenskab|Functionaliteit|功能(.*)</string>
</dict>
</plist>