<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
	</array>
	<key>name</key>
	<string>Rspec plain text story</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#scenario_keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#description</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#story_keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line_keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pending_keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>description</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.language.rspec.story.description</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.language.rspec.story.description</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(As an|As a|I want to|So that)(.*)</string>
		</dict>
		<key>line_keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.language.rspec.story.scenario.line</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(GivenScenario|Given|When|Then|And)\b</string>
		</dict>
		<key>pending_keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.language.rspec.story.scenario.pending.line</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.language.rspec.story.scenario.pending.line</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(Pending)(.*)\b</string>
		</dict>
		<key>scenario_keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.language.rspec.story.scenario</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.language.rspec.story.scenario.title</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(Scenario:)(.*)\b</string>
		</dict>
		<key>story_keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.language.rspec.story</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.language.rspec.story.title</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(Story:)(.*)\b</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s+'([^']+)'[\b\s]+</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.rspec.story</string>
	<key>uuid</key>
	<string>85E2C52C-9B36-4A54-81E7-6D8D3ADAEFA8</string>
	<key>ﬁrstLineMatch</key>
	<string>Story(.*)</string>
</dict>
</plist>
