<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>steps.rb</string>
	</array>
	<key>name</key>
	<string>RSpec Story Steps</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(GivenScenario|Given|When|Then)\b</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.ruby</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ruby.steps</string>
	<key>uuid</key>
	<string>B269B8F3-3A6D-4069-9E70-DD89A679416A</string>
</dict>
</plist>
