<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>.rb</string>
	</array>
	<key>firstLineMatch</key>
	<string>.*"stories".*"helper"</string>
	<key>keyEquivalent</key>
	<string>^~R</string>
	<key>name</key>
	<string>RSpec Story Runner File</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(with_steps_for)\b</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.ruby</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ruby.rspec.story.runner</string>
	<key>uuid</key>
	<string>D35BC28C-98CC-4032-B576-B630B7BDEFB2</string>
</dict>
</plist>
